### ISSUE TITLE
`moment.js` date construction using a non-iso string is deprecated 

### ISSUE THREAD

**Issue by alexdiliberto** [anandts88/ember-validator#1]
`moment.js` deprecation warnings may be triggered during date validation. Issues may occur here https://github.com/anandts88/ember-validator/blob/master/addon/mixins/date.js#L49 and here https://github.com/anandts88/ember-validator/blob/master/ember-validator-non-cli.js#L241.

construction using a non-iso string is deprecated (see https://github.com/moment/moment/issues/1407). One possible fix is to just always provide the native `new Date(...)` constructor as the argument to `moment(...)`.

``` js
moment(new Date("2016/01/01"));
```

**Comment by anandts88** [comment]
@alexdiliberto This will be taken in care in next release. Thanks for the update.

**Comment by anandts88** [comment]
@alexdiliberto This is resolved in 1.3.0. Please validate and let me know so that we can close the issue.
