### ISSUE TITLE
Unique property value.

### ISSUE THREAD

**Issue by Gabiras12** [anandts88/ember-validator#2]
Hi! I've tried to make a custom validation that verifies if the property value is unique in all records on ember-data. 
The problem is that the validators don't wait the findAll promises be resolved to validate de object. Any ideas on how can I make this?

**Comment by anandts88** [comment]
@Gabiras12 This validator is designed with an assumption that we will have all the data before doing validation. In your case we would suggest to make a call to findAll promise in routes model or afterModel hook, so that result of findAll promise will be part of your model.
