### ISSUE TITLE
`this.container` deprecation

### ISSUE THREAD

**Issue by alexdiliberto** [anandts88/ember-validator#3]
If a consuming application using this addon updates to Ember `>=2.3.0`, deprecation messages will be triggered when the following line is hit. https://github.com/anandts88/ember-validator/blob/master/addon/mixin.js#L217

See new `getOwner(this)` API for this specific case http://emberjs.com/deprecations/v2.x/#toc_deprecations-added-in-2-3

Specifically the https://github.com/rwjblue/ember-getowner-polyfill to support a wide array of Ember versions.

**Comment by anandts88** [comment]
@alexdiliberto This is resolved in 1.3.0. Please validate and let me know so that we can close the issue.
