### ISSUE TITLE
Numeric validator is not working for zero value.

### ISSUE THREAD

**Issue by raviganesh12** [anandts88/ember-validator#4]
Numeric validator - "notEqualTo" is not validating if 0 is passed.

**Comment by anandts88** [comment]
@raviganesh12  This is resolved in 1.3.0. Please validate and let me know so that we can close the issue.

**Comment by anandts88** [comment]
@raviganesh12 Please use version 1.3.0

**Comment by raviganesh12** [comment]
@anandts88 Working fine now in 1.3.0. Thanks for a quick turn around.
